create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  full_name text,
  role text,
  workspace text,
  avatar_url text,
  provider text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.profiles enable row level security;

create or replace function public.set_profiles_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;

create trigger profiles_set_updated_at
before update on public.profiles
for each row
execute function public.set_profiles_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    role,
    workspace,
    avatar_url,
    provider
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'role',
    new.raw_user_meta_data ->> 'workspace',
    new.raw_user_meta_data ->> 'avatar_url',
    new.raw_app_meta_data ->> 'provider'
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    role = coalesce(excluded.role, public.profiles.role),
    workspace = coalesce(excluded.workspace, public.profiles.workspace),
    avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
    provider = coalesce(excluded.provider, public.profiles.provider),
    updated_at = timezone('utc', now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user_profile();

drop policy if exists "Profiles can view own row" on public.profiles;
create policy "Profiles can view own row"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Profiles can update own row" on public.profiles;
create policy "Profiles can update own row"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Profiles can insert own row" on public.profiles;
create policy "Profiles can insert own row"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

insert into public.profiles (
  id,
  email,
  full_name,
  role,
  workspace,
  avatar_url,
  provider
)
select
  users.id,
  users.email,
  coalesce(users.raw_user_meta_data ->> 'full_name', users.raw_user_meta_data ->> 'name'),
  users.raw_user_meta_data ->> 'role',
  users.raw_user_meta_data ->> 'workspace',
  users.raw_user_meta_data ->> 'avatar_url',
  users.raw_app_meta_data ->> 'provider'
from auth.users as users
on conflict (id) do update
set
  email = excluded.email,
  full_name = coalesce(excluded.full_name, public.profiles.full_name),
  role = coalesce(excluded.role, public.profiles.role),
  workspace = coalesce(excluded.workspace, public.profiles.workspace),
  avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
  provider = coalesce(excluded.provider, public.profiles.provider),
  updated_at = timezone('utc', now());

create table if not exists public.app_sessions (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users (id) on delete cascade,
  guest_actor_key text,
  prompt text not null default '',
  output text not null default '',
  mode text not null check (mode in ('text', 'image')),
  source text not null check (source in ('composer', 'what-if', 'api')),
  provider text not null,
  response_time_ms double precision not null default 0,
  token_count integer not null default 0,
  trust_score double precision not null default 0,
  clarity_score double precision not null default 0,
  quality_score double precision not null default 0,
  quality_label text not null,
  difference_summary text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint app_sessions_scope_check check (
    (owner_id is not null and guest_actor_key is null)
    or (owner_id is null and guest_actor_key is not null)
  )
);

create index if not exists app_sessions_owner_created_idx
on public.app_sessions (owner_id, created_at desc, id desc);

create index if not exists app_sessions_guest_created_idx
on public.app_sessions (guest_actor_key, created_at desc, id desc)
where guest_actor_key is not null;

alter table public.app_sessions enable row level security;

drop policy if exists "App sessions stay server-routed" on public.app_sessions;
create policy "App sessions stay server-routed"
on public.app_sessions
for all
to anon, authenticated
using (false)
with check (false);

create or replace function public.save_app_session(
  p_actor_key text,
  p_prompt text,
  p_output text,
  p_mode text,
  p_source text,
  p_provider text,
  p_response_time_ms double precision,
  p_token_count integer,
  p_trust_score double precision,
  p_clarity_score double precision,
  p_quality_score double precision,
  p_quality_label text,
  p_difference_summary text default null,
  p_created_at timestamptz default timezone('utc', now())
)
returns table (
  id bigint,
  prompt text,
  output text,
  mode text,
  source text,
  provider text,
  response_time_ms double precision,
  token_count integer,
  trust_score double precision,
  clarity_score double precision,
  quality_score double precision,
  quality_label text,
  difference_summary text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid := auth.uid();
  v_guest_actor_key text := nullif(trim(coalesce(p_actor_key, '')), '');
begin
  if v_owner_id is null and v_guest_actor_key is null then
    raise exception 'Guest actor key is required for public session storage.';
  end if;

  return query
  insert into public.app_sessions (
    owner_id,
    guest_actor_key,
    prompt,
    output,
    mode,
    source,
    provider,
    response_time_ms,
    token_count,
    trust_score,
    clarity_score,
    quality_score,
    quality_label,
    difference_summary,
    created_at
  )
  values (
    v_owner_id,
    case when v_owner_id is null then v_guest_actor_key else null end,
    coalesce(p_prompt, ''),
    coalesce(p_output, ''),
    p_mode,
    coalesce(p_source, 'composer'),
    p_provider,
    greatest(coalesce(p_response_time_ms, 0), 0),
    greatest(coalesce(p_token_count, 0), 0),
    least(greatest(coalesce(p_trust_score, 0), 0), 100),
    least(greatest(coalesce(p_clarity_score, 0), 0), 100),
    least(greatest(coalesce(p_quality_score, 0), 0), 100),
    p_quality_label,
    p_difference_summary,
    coalesce(p_created_at, timezone('utc', now()))
  )
  returning
    app_sessions.id,
    app_sessions.prompt,
    app_sessions.output,
    app_sessions.mode,
    app_sessions.source,
    app_sessions.provider,
    app_sessions.response_time_ms,
    app_sessions.token_count,
    app_sessions.trust_score,
    app_sessions.clarity_score,
    app_sessions.quality_score,
    app_sessions.quality_label,
    app_sessions.difference_summary,
    app_sessions.created_at;
end;
$$;

create or replace function public.list_app_sessions(
  p_actor_key text,
  p_limit integer default 200
)
returns table (
  id bigint,
  prompt text,
  output text,
  mode text,
  source text,
  provider text,
  response_time_ms double precision,
  token_count integer,
  trust_score double precision,
  clarity_score double precision,
  quality_score double precision,
  quality_label text,
  difference_summary text,
  created_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    app_sessions.id,
    app_sessions.prompt,
    app_sessions.output,
    app_sessions.mode,
    app_sessions.source,
    app_sessions.provider,
    app_sessions.response_time_ms,
    app_sessions.token_count,
    app_sessions.trust_score,
    app_sessions.clarity_score,
    app_sessions.quality_score,
    app_sessions.quality_label,
    app_sessions.difference_summary,
    app_sessions.created_at
  from public.app_sessions
  where (
    auth.uid() is not null
    and app_sessions.owner_id = auth.uid()
  ) or (
    auth.uid() is null
    and app_sessions.guest_actor_key = nullif(trim(coalesce(p_actor_key, '')), '')
  )
  order by app_sessions.created_at desc, app_sessions.id desc
  limit greatest(1, least(coalesce(p_limit, 200), 500));
$$;

grant execute on function public.save_app_session(
  text,
  text,
  text,
  text,
  text,
  text,
  double precision,
  integer,
  double precision,
  double precision,
  double precision,
  text,
  text,
  timestamptz
) to anon, authenticated;

grant execute on function public.list_app_sessions(text, integer) to anon, authenticated;
